# Generated by Django 4.1.1 on 2022-09-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModelName',
            new_name='MyJob',
        ),
    ]
