# Generated by Django 4.1.1 on 2022-09-07 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_mymodelname_myjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myjob',
            name='current_job',
        ),
        migrations.AddField(
            model_name='myjob',
            name='my_job',
            field=models.CharField(default=django.utils.timezone.now, help_text='My current job', max_length=15),
            preserve_default=False,
        ),
    ]
